log_level = "INFO"
poc_title = "Vehicle Crash Detection PoC"
poc_af_id = "VehicleCrashDetectionPoC"
poc_app_server = "10.100.0.1"

[net_apis]
api = "camara"
auth_mode = "other"

[camara]
# not protected when net_apis.auth_mode = "other"
url = "http://localhost:8000"
poc_notification_url = "http://localhost:8080"

[nef]
# username and password required when net_apis.auth_mode = "other"
url = "http://localhost:8888"
username = "admin@my-email.com"
password = "pass"
poc_notification_url = "http://host.docker.internal:8080"

[capif_sdk]
capif_username = "username"
capif_password = "password"

[analytics]
offset_period = -5
temporal_gran_size = 5
rep_period = 5

[roboflow]
api_key = "replace_me"

[crash_inference]
model_id = "accident-detection-qgglm/3"
classes = ["Accident", "mild", "moderate", "severe"]
debounce_seconds = 4
intervention_threshold = 0.40
average_car_crash_duration = 0.20 # seconds
inference_server_url = "http://192.168.0.154:9001"
poc_notification_url = "http://192.168.0.180:8080"

[redis]
url = "redis://localhost:6379"
# username = "..."   # optional
# password = "..."   # optional
