[cameras.qos_profiles]
default-camera-profile = {ul_bitrate = "10 Mbps", dl_bitrate = "50 Mbps", qos_profile_name = "default-camera-profile"}
4k-stream-profile      = {ul_bitrate = "10 Mbps", dl_bitrate = "50 Mbps", qos_profile_name = "4k-stream-profile"}

[cameras.qos_profiles_assignment]
default = "default-camera-profile"
6       = "4k-stream-profile"
7       = "4k-stream-profile"

